FROM php:8.2-apache

WORKDIR /var/www/html

COPY . /var/www/html/

RUN mkdir -p /var/www/html/uploads

RUN chmod 777 /var/www/html/data.json
RUN chmod -R 777 /var/www/html/uploads
RUN chown -R www-data:www-data /var/www/html

RUN a2enmod rewrite

EXPOSE 80

CMD ["apache2-foreground"]